docs/api/edgeApi.md, docs/api/logicFlowApi.md, packages/core/src/LogicFlow.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/type/index.ts
Spelling errors `EdgeConifg -> EdgeConfig` and **EdgeConfig** repeat definitions in type/index.ts
=> fix: fix typo and redefined error

docs/article/article02.md, examples/src/pages/usage/approve/components/registerNode.ts
```javascript
validate: (source: BaseNodeModel, target: BaseNodeModel) => {
console.log(source)
console.log(source instanceof BaseNode)
console.log(source instanceof BaseNodeModel)
...
}
```
`source`的类型应该是`BaseNodeModel`,而不是`BaseNode`
=> fix rules validate method param type

packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/util/node.ts, packages/core/src/view/Anchor.tsx
#287 Fix the question that the LoficFlow Base Node is connected alaways not allow when user set the result  from the custom`isAllowConnectedAsSource` or`isAllowConnectedAsTarget` to be boolean.
=> fix(connect validate):Compatible result two formats

package.json, packages/core/package.json, packages/extension/package.json
解决安装依赖时，控制台报许可证无效的问题。
> yarn
yarn install v1.22.10
warning package.json: License should be a valid SPDX license expression
from: https://spdx.org/licenses/
=> Update license to standard format

packages/core/src/model/edge/BezierEdgeModel.ts
在使用贝塞尔曲线连接节点时，当拖动节点时，不再重新计算贝塞尔曲线的控制点，否则会导致贝塞尔曲线的路径被重置。
fixed #303
=> 修复贝塞尔曲线连接的节点，在节点拖动时贝塞尔曲线路径被重置的问题

packages/core/src/view/Anchor.tsx
#320 when edge add successfully,the node’s result of validate from  `isAllowConnectedAsSource ` or `isAllowConnectedAsTarget` may change.But the anchor has cached last result of validate,the  `isAllowConnectedAsSource ` or `isAllowConnectedAsTarget` will no be executed.
So when the edge add into scene,the anchor of edge should clear all cache about   `isAllowConnectedAsSource ` and `isAllowConnectedAsTarget`
=> fix(anchor validate):clear anchor validate cache

packages/extension/src/components/selection-select/index.ts
当右键mousedown实践触发时,会创建选框元素,并在该元素上触发 contextmenu 事件导致出现菜单
=> fix(extension-selection): 修复开启selection后,右键仍会出现上下文菜单的问题

packages/core/src/tool/TextEditTool.tsx
=> fix:编辑状态下的字体样式与非编辑态样式保持一致

packages/extension/examples/group/index.mjs, packages/extension/src/materials/group/GroupNode.ts, packages/extension/src/materials/group/index.ts
允许了`Group`插件中`Group`节点的子节点可以为`Group`类型，支持了：
- 折叠与取消折叠
- 移动Group节点加入
- `GroupNodeModel`中`nestable`参数配置
已知问题：
- 移动`GroupNode`进入另一个`GroupNode`时无法触发`setActiveGroup`高亮显示
=> feat: allow groups being nested by other groups

docs/api/logicFlowApi.md, docs/guide/basic/edge.md, packages/core/src/model/GraphModel.ts, packages/core/src/options.ts, packages/core/src/util/edge.ts, packages/core/src/view/Anchor.tsx, packages/core/src/view/edge/AdjustPoint.tsx
在项目中, 需要特定的节点连线时使用特定的边, 比如:
- 注释节点 使用虚线连接其他节点
- 分支节点连接到其他节点时使用自定义样式的边
此种情况, 使用 `edgeType` 无法满足需求
给 LogicFlow 增加参数 `edgeGenerator`
```ts
export type Definition = {
/**
* 节点间连线、连线变更时的边的生成规则
* @param sourceNode 起始节点数据
* @param targetNode 终止节点数据
* @param currentEdge 当前边的数据, 仅移动已有边的时候有值
*
* @return undefined: 使用默认边
*        string: 自定义边类型
*        any: 自定义边及其他数据
*/
edgeGenerator?: (sourceNode: any, targetNode: any, currentEdge?: any) => string | any | undefined;
}
```
```js
const lf = new LogicFlow({
...,
// 默认边
edgeType: 'bezier',
// 移动已有边时会有 currentEdge 信息, 否则为空
edgeGenerator: (sourceNode, targetNode, currentEdge) => {
// 起始节点类型 rect 时使用 自定义的边 custom-edge
if (sourceNode.type === 'rect') return 'custom-edge'
}
})
```
文档和示例可能还需要再完善下 😄
=> feat: 增加 edgeGenerator 选项, 可自定义连边规则

packages/core/src/model/edge/BaseEdgeModel.ts
调整 BaseEdgeModel 的构造函数的属性初始化顺序, 修正在构造边实例的时候无法通过 initEdgeData 和 setAttributes 去自定义 文本 的问题.
修正前, 实现自定义文本办法
```js
class BranchEdgeModel extends PolylineEdgeModel {
initEdgeData(data: any): void {
super.initEdgeData(data)
// 保证 formatText 能在初始化时拿到自定义的 文本
data.text = this.properties.title || ''
}
setAttributes() {
this.updateText(this.properties.title)
}
}
```
修正后:
```js
class BranchEdgeModel extends PolylineEdgeModel {
setAttributes() {
this.updateText(this.properties.title)
}
}
```
=> fix: 修正 BaseEdgeModel 构造函数属性初始化顺序

packages/extension/examples/NodeResize/index.html, packages/extension/examples/NodeResize/index.mjs, packages/extension/src/NodeResize/Control/Control.tsx, packages/extension/src/NodeResize/Node/DiamondResize.tsx, packages/extension/src/NodeResize/Node/EllipseResize.tsx, packages/extension/src/NodeResize/Node/HtmlResize.tsx, packages/extension/src/NodeResize/Node/RectResize.tsx
提供 enableProportionResize() 方法开启/关闭等比缩放功能；
支持 RectResize、HtmlResize、EllipseResize、DiamondResize 等比拖拽缩放；
不影响原有基础功能；
修复椭圆和菱形（左上、左下、右上）拖拽时的BUG ；
已测试四个角的缩放效果，以及撤销/删除/回退等情况的影响；
=> ResizeNode 等比缩放功能合并

examples/src/pages/extension/components/dnd-panel/index.tsx, packages/extension/src/components/dnd-panel/index.ts
不改变`setPatternItems`的`options`，通过修改`DNDPanel`，给el添加事件，并触发`emit`，来实现dndPanel添加额外事件
=> feat: add event to dnd-penal

packages/core/src/LogicFlow.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/view/behavior/DnD.ts
拖拽新增节点时，保证只触发一次emit事件，通过添加addNode第二个参数，来变更eventType，减少不必要的事件触发
=> feat: Modify the addNode event type

packages/core/src/model/edge/BaseEdgeModel.ts
文档示例无法显示 [边上插入节点 InsertNodeInPolyline](http://logic-flow.org/guide/extension/extension-insert-node-in-polyline.html#%E5%8A%9F%E8%83%BD)
并报错：TypeError: Cannot read properties of null (reading 'x')
**原因：**
**twoPointDistance无法获取target参数**
计算两个节点相连是起点位置：getBeginAnchor
和计算两个节点相连是终点位置：getEndAnchor 
传入参数target 为null
=> fix: twoPointDistance无法获取target参数

packages/core/src/index.tsx
将core/constant/constant.ts中定义的ElementState, ModelType, ElementType, EventType导出，方便第三方代码能使用其中定义的常量
=> export ElementState ModelType ElementType EventType from constant.ts

packages/core/index.html, packages/core/src/view/Anchor.tsx
之前是：
```javascript
{
e: {
event: EventObject
},
data: ....
}
```
优化后是：
```javascript
{
e: EventObject,
data: ...
}
```
=> anchor的drop和dragend事件的参数传递优化成event对像不嵌套在e对像下

packages/core/src/view/text/LineText.tsx
close [https://github.com/didi/LogicFlow/issues/1151](https://github.com/didi/LogicFlow/issues/1151)
**问题发生原因**：
1. `Text.tsx`有进行`overflowMode="ellipsis"`的逻辑处理，使用`textWidth`作为文本宽度
2. `LineText.tsx`的`getBackground()`没有进行`overflowMode="ellipsis"`的逻辑处理，宽度计算错误
**解决方法**：
1. 仿造`Text.tsx`进行`overflowMode="ellipsis"`的逻辑处理，使用`textWidth`作为文本宽度
=> fix(core): fix the background width of the text on the side is not displayed correctly in ellipsis mode(#1151)

packages/core/src/model/EditConfigModel.ts
close [https://github.com/didi/LogicFlow/issues/1180](https://github.com/didi/LogicFlow/issues/1180)
**问题发生原因**：
1. 每次`isSilentMode=true`的时候，都会进行当前状态`config`的保存
2. 当触发第二次`isSilentMode=true`时，会进行`isSilentMode=true`状态的保存（实际上应该保存`isSilentMode=false`->`isSilentMode=true`时的当前状态），当切换到`isSilentMode=false`时，会进行状态的回滚（但是此时`this.defaultConfig`已经错误，为`isSilentMode=true`时的状态）
**解决方法**：
1. 检测到`isSilentMode=true`重复赋值时，进行`this.defaultConfig`的赋值阻止
=> fix(core): prevent isSilentMode=true from calling repeatedly(#1180)

packages/extension/src/tools/snapshot/index.ts
What to solve:
When we want to capture a snapshot of the process diagram, we may not obtain the intended snapshot if the diagram is scaled, because when drawing elements on the canvas, the impact of scaling on the translation operation was not taken into consideration.
How to solve: 
Just multiply the calculated displacement by the scaling factor.
```javascript
translation *  (1 / zoom)
```
=> fix: Both translateX and translateY need to be multiplied by the scaling factor when redrawing elements on the canvas to generate a snapshot.

packages/extension/src/components/control/index.ts
=> fix: 修正Control移除item不正确的问题

packages/core/index.html, packages/core/src/util/edge.ts, packages/core/src/util/sampling.ts, packages/core/src/view/edge/BezierEdge.tsx
close https://github.com/didi/LogicFlow/issues/951
由于贝塞尔曲线的箭头之前是直接使用0.95采样点和终点作为箭头的方向，当遇两个节点距离过远且控制点太短的时，就会出现箭头的方向和曲线差别很大的情况。
从0.98采样点开始，计算到0.5，取第一个满足和终点距离大于offset的采样点。通过这两个点计算出来的方向能保证箭头垂点和曲线尽量重合。经过统计在大多数情况下只需要计算2-5既可以得出采样点（曲线越短，计算次数越多），所以性能影响不大。
=> fix(core): improve the appearance of Bezier curve arrows.(#951)

packages/extension/src/materials/group/index.ts
close [https://github.com/didi/LogicFlow/issues/1261](https://github.com/didi/LogicFlow/issues/1261)
如[issues/1261重现代码](https://codesandbox.io/s/pensive-rosalind-6567fk?file=/src/index.js:1388-1547)所示，当我们框选元素时，会触发
```js
lf.addNode({
type: "select-group",
x: x1 + width / 2,
y: y1 + height / 2,
width,
height,
children: nodes.map((item) => item.id)
});
```
`lf.addNode()`会触发下面代码的执行
```js
// packages/extension/src/materials/group/index.ts
lf.on('node:add,node:drop,node:dnd-add', this.appendNodeToGroup);
appendNodeToGroup = ({ data }) => {
//...
const nodeModel = this.lf.getNodeModelById(data.id);
const bounds = nodeModel.getBounds();
const group = this.getGroup(bounds, data);
if (!group) return;
//...
if (nodeModel.isGroup) {
// 如果这个节点是分组，那么将其子节点也记录下来
data.children.forEach((nodeId) => { …
```
=> fix(extension): nodeGroupMap was not set correctly when adding a group

packages/extension/src/tools/snapshot/index.ts
close [https://github.com/didi/LogicFlow/issues/1222](https://github.com/didi/LogicFlow/issues/1222)
SVG坐标系有两个重要的属性：`viewport`， `viewBox`
```js
<div style="width: 200px; height: 200px">
<div>没有使用viewBox进行缩放：svg的viewport < 内部元素的宽高</div>
<svg width="100%" height="100%" style="background:#889cee">
<circle cx="100" cy="100" r="200" fill="#ff0036"></circle>
</svg>
</div>
<div style="width: 200px; height: 200px">
<div>没有使用viewBox进行缩放：svg的viewport > 内部元素的宽高 </div>
<svg width="100%" height="100%" style="background:#889cee">
<circle cx="50" cy="50" r="50" fill="#ff0036"></circle>
</svg>
</div>
<div style="width: 200px; height: 200px">
<div>使用内部元素的viewBox进行缩放：svg的viewport > 内部元素的宽高</div>
<svg width="100%" height="100%" style="background:#889cee" viewBox="0 0 100 100">
<circle cx="50" cy="50" r="50" …
```
=> fix(extension): ensure dpr>=1 when exporting images(#1222)

packages/engine/src/nodes/BaseNode.ts
bug：uuid 创建的 NodeId 为 xxxx-xxxx-xxxx-zzzz 格式，eval 执行时会将 - 识别为数学减号，导致执行报错
解决方案：将 nodeId 中的 '-' 移除
=> fix: 修复 uuid 生成的 id 以 '-' 分隔，在 eval 执行时会报错的 bug

packages/core/src/LogicFlow.tsx, packages/core/src/model/EditConfigModel.ts, packages/core/src/model/GraphModel.ts, packages/core/src/model/TransformModel.ts, packages/core/src/view/behavior/DnD.ts, packages/core/src/view/overlay/CanvasOverlay.tsx, packages/extension/src/components/menu/index.ts
feat:
1. add draggable range for graph #1337 
```typescript
stopMoveGraph?: boolean | 'vertical' | 'horizontal' | [number, number, number, number];  // [minX, minY, maxX, maxY]
// as: 
//  false: [-Infinity, -Infinity, Infinity, Infinity],
//  true: [0, 0, 0, 0],
//  vertical: [Infinity, 0, -Infinity, 0]
//  horizontal: [0, Infinity, 0, -Infinity]
// for example:
stopMoveGraph: [-20, -50, 40, 100]
// as:
//  -50 <= translate of the graph in y-axis < = 100
//  -20 <= translate of the graph in x-axis < = 40
``` 
fix:
1. make graph read-only after setting silent mode #1335
=> add draggable range for graph(#1337)

docs/api/logicFlowApi.md, packages/core/src/model/GraphModel.ts, packages/core/src/options.ts, packages/core/src/view/Anchor.tsx
由于当前从锚点拖出的连线只支持直线，效果不佳，能否在`LogicFlow`配置项中加一个`getAnchorLine`参数供用户自定义，通过用户自己调用`h`函数来自定义路径
=> feat: 支持自定义从锚点拖出的连线路径

packages/core/src/view/Anchor.tsx
anchor:dragend 事件参数增加 edgeModel 参数，便于用户在事件中区分锚点连线是否连接到一个已有节点。
用于实现一些功能，例如从某个节点拖出连线，释放鼠标时在释放位置自动创建新节点，此时需要判断鼠标释放时是否已经连接到已存在的节点。
=> feat: anchor dragend事件参数增加edgeModel

packages/core/src/LogicFlow.tsx, packages/core/src/constant/constant.ts, packages/core/src/keyboard/shortcut.ts, packages/extension/src/materials/group/index.ts
fix: [https://github.com/didi/LogicFlow/issues/1346](https://github.com/didi/LogicFlow/issues/1346)
目前`packages/extension/src/materials/group/index.ts`的逻辑是在原有的`LogicFlow.addElements()`基础上进行扩充，但是选择`Group`时，拿到的数据是:
```json
{
"nodes": [
{
"id": "node_group",
"type": "my-group",
"x": 400,
"y": 400,
"children": ["node_item1", "node_item2"]
}
],
"edges": []
}
```
因此在目前的代码（下面的代码）中，拿到的`children`只有`nodes`数据，或者这么说，目前并没有把`edges`数据放入到`xx.children`中，因此单纯遍历`xx.children`只能复制`nodes`数据
```js
for (let i = 0; i < nodes.length; i++) {
const node = nodes[i];
const preId = node.id;
const { children, ...rest } = node;
const nodeModel = lf.addNode(rest);
const fn = (children: Set<string>, current: BaseNodeModel) => {
children?.forEach((childId: string) => {
const childNodeModel = lf.getNodeModelById(childId); …
```
=> fix: add edge copying when copying a group(#1346)

packages/extension/src/materials/group/index.ts
[https://github.com/didi/LogicFlow/issues/1379](https://github.com/didi/LogicFlow/issues/1379)
之前写的时候，原先规划是group内部节点模仿外部nodes和edges进行整体偏移，大体逻辑为
```js
// 构建的时候直接偏移，这里不需要再进行再度偏移
// groupInnerChildren.nodes.forEach(node => this.translationNodeData(node, distance));
// groupInnerChildren.edges.forEach(edge => this.translationEdgeData(edge, distance));
```
后面改成在外部进行偏移，然后传入具体的偏移值，这样直接创建的时候就可以进行偏移，不用创建完成后，又再度偏移一次
但是忘记了将最外层`edges`的偏移量去除，因为在原来的`shortcut.ts`中就已经偏移
```js
keyboard.on(['cmd + v', 'ctrl + v'], () => {
if (!keyboardOptions.enabled) return true;
if (graph.textEditElement) return true;
if (selected && (selected.nodes || selected.edges)) {
lf.clearSelectElements();
const addElements = lf.addElements(selected, CHILDREN_TRANSLATION_DISTANCE);
if (!addElements) return true; …
```
=> fix(extension): the outermost edges translate 0 when copy a group(#1379)

packages/core/src/util/drag.ts, packages/core/src/util/mobx.ts, packages/core/src/view/node/BaseNode.tsx
close [https://github.com/didi/LogicFlow/issues/1370](https://github.com/didi/LogicFlow/issues/1370)
当使用撤销功能：`LogicFlow.undo()`时，会重新初始化所有`nodes`数据，触发`node`对应的`model`数据的重新构建，即`LogicFlow.undo()`时会新构建一个model对象
```ts
// packages/core/src/LogicFlow.tsx
undo() {
if (!this.history.undoAble()) return;
// formatData兼容vue数据
const graphData = formatData(this.history.undo());
this.clearSelectElements();
this.graphModel.graphDataToModel(graphData);
}
// packages/core/src/model/GraphModel.ts
graphDataToModel(graphData: GraphConfigData) {
//...
if (graphData.nodes) {
this.nodes = map(graphData.nodes, (node) => {
const Model = this.getModel(node.type);
//...
return new Model(node, this);
});
} else {
this.nodes = [];
}
//...
}
```
从而触发`packages/core/src/view/Graph.tsx`的`render()`重新执行
```js …
```
=> fix(core): refresh the value of model when mouse down(#1370)

packages/core/src/model/edge/BaseEdgeModel.ts, packages/extension/examples/insert-node-in-polyline/NotAllowConnectRect.mjs, packages/extension/examples/insert-node-in-polyline/index.html, packages/extension/examples/insert-node-in-polyline/index.js, packages/extension/src/insert-node-in-polyline/index.ts
close [https://github.com/didi/LogicFlow/issues/1077](https://github.com/didi/LogicFlow/issues/1077)
参照[https://github.com/didi/LogicFlow/issues/454](https://github.com/didi/LogicFlow/issues/454)，当用户自定义`getDefaultAnchor(){return []}`时，表示：不显示锚点，也不允许其他节点连接到此节点
```js
class NotAllowConnectRectModel extends RectNodeModel {
getDefaultAnchor () {
return [];
}
}
```
而`insert-node-in-polyline`没有对这方面进行处理，当用户使用自定义的节点（不显示锚点，也不允许其他节点连接到此节点），然后插入到两个节点之间的`edge`时，会触发`insetNode()`方法，从而触发
```js
// packages/extension/src/insert-node-in-polyline/index.ts
for (let i = 0; i < edges.length; i++) {
// eslint-disable-next-line max-len
const { crossIndex, crossPoints } = isNodeInSegment(
nodeModel,
edges[i],
this.deviation,
);
if (crossIndex >= 0) {
//...
this._lf.deleteEdge(id);
this._lf.addEdge({
type, …
```
=> fix: prevent node without anchors using InsertNodeInPolyline(#1077)

packages/core/src/style/index.css
=>  修复：缩放快捷键 CTRL + 滚轮会触发浏览器事件（使用选区当框选后）

packages/extension/src/tools/snapshot/index.ts
同 https://github.com/apache/echarts/pull/12643
在qiankun、wujie等微前端框架中，子应用获取到的window是一个proxy对象
当LogicFlow在子应用中加载时，会导致触发下载的方法中新建点击事件失败，进而导致下载图片报错
因此将view字段的值从直接取window改为取document.defaultView
=> fix:修复在qiankun等微前端框架中在子应用里使用时下载方法报错的问题

packages/core/src/LogicFlow.tsx, packages/core/src/keyboard/index.ts, packages/core/src/view/behavior/DnD.ts
=> fix: 修复静默模式切换后快捷键和拖拽节点状态不更新问题

packages/core/src/view/node/BaseNode.tsx
修复[issue#1071](https://github.com/didi/LogicFlow/issues/1071)：笔记本触摸板点击节点时并没有触发node:click事件。
原代码判断逻辑为：mousedown和click间隔时间大于200ms，则认为是拖拽，不触发click事件。
这样判断并不是最优方式， 原因：
1.当使用触摸板点击时，时间间隔大于200ms，具体是210ms-240ms之间，导致没有触发node:click事件。
2.当单次拖拽操作很短的情况下（在200ms内），按照原代码，会触发node:click事件，这与期望不符。
本次提交的改动：对节点增加mouseup监听，对拖拽状态isDragging状态进行记录，在handleClick中进行判断，确保在鼠标及触摸板点击时都能正常触发node:click事件。
=> fix:修复笔记本触摸板点击节点事件失效

packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/PolylineEdgeModel.ts
修复[issue#1541](https://github.com/didi/LogicFlow/issues/1541)
之前开发也发现了这个问题，当边为polyline(或polyline继承边)时就会出现这种情况。原因是框选拖动时，polyline的轨迹pointsList没有进行整体移动，本次提交的改动可以修复这个缺陷
=> fix:修复polyline调整后，被框选拖动而出现回退的问题

packages/core/src/style/index.css, packages/extension/src/components/selection-select/index.ts
本地构建项目失败没能启动项目来测试这个改动是否能真真正正的解决该问题，但在 #1533 提供的[示例](https://github.com/ChangeSuger/logicflow-bug-report)基础上做过测试，具体来说是：
1. 手动选区，创建选区元素，然后通过 DevTool 取消选区元素的该样式
https://github.com/didi/LogicFlow/blob/bc553cb959aed494a6e52f75634a3bda88f1cd29/packages/core/src/style/index.css#L192
2. 在控制台输入以下代码：
```js
document.querySelector('.lf-multiple-select').addEventListener('wheel', (ev) => {
ev.preventDefault();
const newEvent = new WheelEvent('wheel', {
deltaX: ev.deltaX,
deltaY: ev.deltaY,
clientX: ev.clientX,
clientY: ev.clientY,
ctrlKey: ev.ctrlKey,
});
document.querySelector('div#lf-view').querySelector('.lf-canvas-overlay[name="canvas-overlay"]').dispatchEvent(newEvent);
}, { passive: false });
```
PR 中的更改与上述操作相似。
=> fix: 修复选区插件无法触发鼠标事件的问题，同时兼容 Ctrl + 滚轮事件

packages/core/__tests__/bugs/1545-spec.test.ts, packages/core/__tests__/model/graphmodel.test.ts, packages/core/src/model/GraphModel.ts
fix [#1545](https://github.com/didi/LogicFlow/issues/1545)
fix [#1440](https://github.com/didi/LogicFlow/issues/1440)   => related: [transform相关问题汇总](https://github.com/didi/LogicFlow/issues/1446)
在`menu`鼠标右键点击复制时，会触发
```js
// packages/core/src/LogicFlow.tsx
cloneNode(nodeId) {
const Model = this.graphModel.getNodeModelById(nodeId);
const data = Model.getData();
const { guards } = this.options;
const enabledClone = guards && guards.beforeClone ? guards.beforeClone(data) : true;
if (enabledClone) {
return this.graphModel.cloneNode(nodeId);
}
}
```
最终执行逻辑也就是`this.graphModel.cloneNode(nodeId)`
```js
// packages/core/src/model/GraphModel.ts
cloneNode(nodeId) {
const Model = this.getNodeModelById(nodeId);
const data = Model.getData();
data.x += 30;
data.y += 30;
//...
if (data.text) { …
```
=> fix(core): snap the text pos of cloneNode to grid(#1545)

packages/extension/src/NodeResize/Control/Control.tsx
related: [transform相关问题汇总](https://github.com/didi/LogicFlow/issues/1446)
fix: [#1384](https://github.com/didi/LogicFlow/issues/1384)
fix: [#1417](https://github.com/didi/LogicFlow/issues/1417)
这次`pr`不是重构缩放、旋转等transform操作相关逻辑，只是一个简单的`bug修复`，因为这个`bug`的产生是因为我之前[pr#1205](https://github.com/didi/LogicFlow/pull/1205)疏忽大意导致的问题
在上次[pr#1205](https://github.com/didi/LogicFlow/pull/1205)中，我在`onDragEnd()`中增加了一行代码`this.updateEdgePointByAnchors()`，代表的意思是：更新目前node节点所有连接的edge的所有连接点，如下面所示
```js
// packages/extension/src/NodeResize/Control/Control.tsx
onDragEnd = () => {
// 先触发onDragging()->更新边->再触发用户自定义的getDefaultAnchor()，所以onDragging()拿到的anchors是滞后的
// 为了正确设置最终的位置，应该在拖拽结束的时候，再设置一次边的Point位置，此时拿到的anchors是最新的
+++   this.updateEdgePointByAnchors();
const { gridSize = 1 } = this.graphModel;
const x = …
```
=> fix(extension): trigger updateEdgePointByAnchors() after moveTo(#1384)

packages/extension/src/materials/group/index.ts
fix [#1535](https://github.com/didi/LogicFlow/issues/1535)
在[https://examples.logic-flow.cn/demo/dist/pool](https://examples.logic-flow.cn/demo/dist/pool)的调试中，发现两个`GroupNode`类型的`Node`数据的初始化`zIndex=1`
当点击右边的矩形时，会触发`node:click`方法，一共有两个地方
```js
// packages/core/src/view/node/BaseNode.tsx
handleClick = (e) => {
//...
if (model.isSelected && !isDoubleClick && isMultiple) {
//...
} else {
graphModel.selectNodeById(model.id, isMultiple);
eventOptions.isSelected = true;
this.toFront();
}
//...
};
toFront() {
const { model, graphModel } = this.props;
if (model.autoToFront) {
graphModel.toFront(model.id);
}
}
```
由于`GroupNode`类型的`Node`默认`autoToFront=false`，因此不会触发上面代码中的`graphModel.toFront(model.id)`
```js
class GroupNodeModel extends RectResize.model {
initNodeData(data) {
//...
this.autoToFront = …
```
=> fix(extension): perform topGroupZIndex calibration when add node(#1535)

examples/feature-examples/.umirc.ts, examples/feature-examples/src/pages/extensions/snapshot/ImageNode.ts, examples/feature-examples/src/pages/extensions/snapshot/index.less, examples/feature-examples/src/pages/extensions/snapshot/index.tsx, packages/extension/src/tools/snapshot/index.ts
关联的 issue: https://github.com/didi/LogicFlow/issues/477 https://github.com/didi/LogicFlow/issues/1076
Snapshot 插件支持导出节点中的网络图片。
之前按照 issue 中的建议，使用 html2Canvas 和 dom-to-image 均无法正确导出节点中的图片。
在公司项目开发中通过在调用 getSnapshot() 之前将   标签的图片替换成 base64 字符串, 将 style 中的 background, background-image 替换成 base64 字符串, 可以正确导出节点中的图片。
测试范围覆盖了 getSnapshot, getSnapshotBase64, getSnapshotBlob, 均成功导出带有网络图片的节点。
=> feat(extension): 支持导出节点中的网络图片

examples/feature-examples/src/pages/extensions/snapshot/index.tsx, packages/extension/src/tools/snapshot/index.ts
- snapshot 插件注释丰富，cloneSvg 函数封装优化
- snapshot 的示例增加背景色控制
> 最近正好在看 Canvas 相关的东西，第一反应想到的就是 Snapshot 插件可能是基于 Canvas 实现的😄
---
https://github.com/didi/LogicFlow/blob/84cd725ba453006d75c365ddb790c302719825d6/packages/extension/src/tools/snapshot/index.ts#L258-L260
@FanSun521 cloneSvg 增加样式的方式是增加样式节点，会改变 copy.lastChild 的指向
明白了～
https://github.com/didi/LogicFlow/blob/84cd725ba453006d75c365ddb790c302719825d6/packages/extension/src/tools/snapshot/index.ts#L315-L317
=> feat: snapshot插件小优化

examples/feature-examples/src/pages/extensions/selection-select/index.tsx, packages/core/src/model/TransformModel.ts, packages/core/src/view/overlay/CanvasOverlay.tsx
fix: https://github.com/didi/LogicFlow/issues/1700
=> fix(core): 修复画布拖动阻止滚动

packages/core/src/tool/MultipleSelectTool.tsx, packages/extension/src/components/selection-select/index.ts
fix #1614 
fix #1534 
之前兼容鼠标滚轮事件的方式会阻塞整个页面的滚轮事件，已修复
=> fix: 修复使用框选插件会阻塞页面滚轮事件问题

examples/feature-examples/src/components/nodes/custom-circle/index.ts, examples/feature-examples/src/components/nodes/custom-diamond/index.tsx, examples/feature-examples/src/components/nodes/custom-ellipse/index.tsx, examples/feature-examples/src/components/nodes/custom-polygon/index.tsx, examples/feature-examples/src/components/nodes/custom-rect/index.tsx, examples/feature-examples/src/pages/graph/index.tsx, packages/core/src/model/node/CircleNodeModel.ts, packages/core/src/model/node/DiamondNodeModel.ts, packages/core/src/model/node/EllipseNodeModel.ts, packages/core/src/model/node/PolygonNodeModel.ts, packages/core/src/model/node/RectNodeModel.ts, sites/docs/docs/tutorial/basic/node.en.md, sites/docs/docs/tutorial/basic/node.zh.md
- 修复circle、diamond、polygon、rect、ellipse 中 initNodeData 方法不生效 #1775 
- 修复官网教程- 基础教程- 节点文章中跳转错误
- example中补充自定义circle、diamon、polygon节点
=> fix(core&site): 修复自定义节点 Model 中 initNodeData 方法不生效

.gitignore, examples/demo.html, package.json, packages/vue-node-registry/src/model.ts, pnpm-lock.yaml, rollup.config.js, sites/docs/.dumi/global.ts, sites/docs/.dumirc.ts, sites/docs/docs/tutorial/extension/group.en.md, sites/docs/docs/tutorial/extension/insert-node-in-polyline.en.md, sites/docs/docs/tutorial/extension/insert-node-in-polyline.zh.md, sites/docs/package.json, sites/docs/tsconfig.json, tsconfig.json
- 升级 rollup 以及相关 plugins 版本，用于解决 build:umd 时 souceMap 失败的问题
- 增加 visualizer 包用于分析打包产物
- 修复 model 中 width/height/radius 等 properties 传 0 无效的 bug
- docs 中 global.ts 中依赖加载通过 import 引入，之前通过 require 引入会导致 tree-shaking 失效
- 修复文档中 core 包 css 资源地址错误的问题  close #1798
=> docs: 优化 docs 项目打包，减少包体积，修复若干 bug

package.json
在 build:watch:esm 和 build:watch:cjs 脚本中添加反斜杠，
以确保命令在各种环境中正确执行。这个修改提高了构建过程的可靠性和跨平台兼容性。
Closes #1818
=> fix(build): 修正 build:watch 脚本中的命令格式

sites/docs/docs/tutorial/extension/adapter.en.md, sites/docs/docs/tutorial/extension/adapter.zh.md, sites/docs/docs/tutorial/get-started.en.md, sites/docs/docs/tutorial/get-started.zh.md
- 获取画布数据源 api 补充到快速上手页 #1796
效果如下：
- 修复文档文字加粗格式错误
=> docs(site): 获取画布数据 api 补充到快速上手页

sites/docs/docs/article/extension/snapshot.en.md, sites/docs/docs/article/extension/snapshot.zh.md
=> docs(site): 优化 snapshot 文章内容和图片

sites/docs/docs/tutorial/get-started.en.md, sites/docs/docs/tutorial/get-started.zh.md
=> fix(site): 文档勘误，插件的cdn使用方式错误

packages/core/src/util/graph.ts
When using `@logicflow/core@2.0.4` with Angular v18 project, the angular compiler throws the following error:
```
✘ [ERROR] TS2307: Cannot find module 'src/model' or its corresponding type declarations. [plugin angular-compiler]
node_modules/@logicflow/core/lib/util/graph.d.ts:1:32:
1 │ import { EditConfigModel } from 'src/model';
```
This is because, for this particular file the import path was not given in relative style. This PR fixes this minor issue.
=> fix(core): update import path to relative path style to remove compilation error in angular

packages/core/src/model/node/BaseNodeModel.ts, packages/extension/src/dynamic-group/index.ts, packages/extension/src/dynamic-group/node.ts
related:  [https://github.com/didi/LogicFlow/issues/1826](https://github.com/didi/LogicFlow/issues/1826)
> 注：本次pr建立在`rotate=0`的情况下，还没涉及到`rotate不等于0`的适配，因为涉及到`bbox`的调整，需要后续再优化`rotate不等于0`的情况....
目前`dynamic-group`的`resize`操作存在两个问题：
1. `group`里面的`item`没有按照比例进行缩放
2. `group`缩放时，会触发`this.x`和`this.y`的改变，同时也会触发`group.item`的`this.x`和`this.y`改变，然后`group`的`resize`再次出发`group.item`的`this.x`和`this.y`的改变，从而造成了两倍，也就是`this.x=this.x+2*deltaX`
由于比较简单，因此这里不再做详细分析，如下图所示，应该根据group.item.width在group.width所占的比例进行deltaX的换算
```ts
class BaseNodeModel {
resize(resizeInfo: ResizeInfo): ResizeNodeData {
const { width, height, deltaX, deltaY } = resizeInfo;
// 移动节点以及文本内容
this.move(deltaX / 2, deltaY / 2);
//...
}
move(deltaX: number, deltaY: number, isIgnoreRule = false): boolean {
const { isAllowMoveX, isAllowMoveY } = …
```
=> fix(extension): 【dynamic-group】修复resize和move的冲突问题(#1826)

examples/feature-examples/src/pages/graph/index.tsx, packages/core/src/algorithm/rotate.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/util/resize.ts, packages/core/src/view/Control.tsx
related: [transform相关问题汇总](https://github.com/didi/LogicFlow/issues/1446)
fix: [https://github.com/didi/LogicFlow/issues/1428](https://github.com/didi/LogicFlow/issues/1428)
fix: [https://github.com/didi/LogicFlow/issues/1628](https://github.com/didi/LogicFlow/issues/1628)
fix: [https://github.com/didi/LogicFlow/issues/1813](https://github.com/didi/LogicFlow/issues/1813)
fix: [https://github.com/didi/LogicFlow/issues/1475](https://github.com/didi/LogicFlow/issues/1475)
node 加入`rotate`后，可能影响的范围有：
1. rotate + resize=>正常 resize 模式
2. rotate + resize=>等比例 resize 模式
3. rotate + bbox 调整 => 涉及到旋转后辅助线对齐
4. rotate + bbox 调整 => 涉及到点是否在某个旋转图形内的判断
5. rotate + bbox 调整 => 涉及到 anchor 与 anchor 连线的计算
---
本次 pr 主要针对 rotate + resize 的正常 resize 模式进行修复
1. [x] rotate + resize=>正常 resize 模式 …
=> fix(core): node => rotate+正常模式resize(#1428)

packages/extension/src/dynamic-group/model.ts
fix [https://github.com/didi/LogicFlow/issues/1810](https://github.com/didi/LogicFlow/issues/1810)
每次从`history`拿出数据后，都会触发`nodes`的重新渲染，然后触发`new Model()`
然后每次都会触发一次`setAttributes()`->`toggleCollapse()`->触发折叠后的坐标计算
```ts
class DynamicGroupNodeModel {
constructor(data: NodeConfig<IGroupNodeProperties>, graphModel: GraphModel) {
super(data, graphModel);
this.childrenLastCollapseStateDict = new Map();
this.initNodeData(data);
this.setAttributes();
}
setAttributes() {
super.setAttributes();
// 初始化时，如果 this.isCollapsed 为 true，则主动触发一次折叠操作
if (this.isCollapsed) {
this.toggleCollapse(true);
}
}
}
```
```ts
// 折叠操作
collapse() {
const { x, y, text, width, height, collapsedWidth, collapsedHeight } = this
this.x = x - width / 2 + collapsedWidth / 2
this.y = y - height / 2 + collapsedHeight / 2 …
```
=> fix(extension): 【dynamic-group】存入history时，将text坐标恢复到未折叠前的数据(#1810)

packages/core/src/model/BaseModel.ts, packages/core/src/model/GraphModel.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/util/resize.ts, packages/extension/src/dynamic-group/index.ts, packages/extension/src/dynamic-group/model.ts, packages/extension/src/dynamic-group/node.ts, sites/docs/docs/tutorial/extension/dynamic-group.en.md, sites/docs/docs/tutorial/extension/dynamic-group.zh.md
related 
- https://github.com/didi/LogicFlow/issues/1446
- https://github.com/didi/LogicFlow/issues/1442
- https://github.com/didi/LogicFlow/issues/937
以及
- https://github.com/didi/LogicFlow/issues/1826
本次提交是`feature`，主要复用目前存在的`isRestrict`和`transformWithContainer`属性，实现分组缩放限制以及控制子元素是否需要同时缩放的功能
> 由于`rotate`相关逻辑需要很大工作量进行`bbox`的调整，因此本次提交仍然只针对`rotate=0`的情况，后续再进行`rotate`相关逻辑的优化
- feat：仿造moveRules，增加resizeRules规则进行节点resize限制
- feat：完善transformWidthContainer参数控制子元素是否需要同时缩放的逻辑
- chore: transformWidthContainer->transformWithContainer
- feat：isRestrict模式下增加resize限制逻辑-根据内容占地位置来限制缩小范围
- docs：增加isRestrict新的限制说明+transformWithContainer的说明
在原来LogicFlow代码逻辑中，有`moveRules`可以进行移动相关的限制判断，如果不满足条件，则不允许进行移动
而分组缩放限制本质也是一种`resize`限制相关的需求，因此仿造moveRules，增加resizeRules规则进行节点resize限制 …
=> feat(extension):【dynamic-group】isRestrict分组缩放限制+transformWidthContainer控制子元素是否需要同时缩放

packages/extension/src/dynamic-group/index.ts, packages/extension/src/dynamic-group/model.ts
close [https://github.com/didi/LogicFlow/issues/1750](https://github.com/didi/LogicFlow/issues/1750)
在原来的代码中，有对应的`autoResize`的注释和初始化代码，比如
```ts
export type IGroupNodeProperties = {
/**
* 子节点是否限制移动范围
* 默认为 false，允许拖拽移除分组
*/
isRestrict?: boolean
/**
* isRestrict 模式启用时，
* 如果同时设置 autoResize 为 true，
* 那么子节点在父节点中移动时，父节点会自动调整大小
*/
autoResize?: boolean
} & IRectNodeProperties
export class DynamicGroupNodeModel extends RectNodeModel<IGroupNodeProperties> {
initNodeData(data: LogicFlow.NodeConfig<IGroupNodeProperties>) {
super.initNodeData(data)
const {
isRestrict,
autoResize,
//...
} = data.properties ?? {}
this.isRestrict = isRestrict ?? false
this.autoResize = autoResize ?? false
//...
}
}
```
包括在`dynamic-group.zh.md`和`dynamic-group.en.md`都有对`autoResize`属性的说明，但是并没有真正实现该功能 …
=> feat(extension): 【dynamic-group】实现autoResize自动扩展父节点的功能(#1750)

packages/core/src/view/text/BaseText.tsx
> 回答 ISSUE #1891 时发现节点或边的文本拖拽时存在未能完全跟随鼠标移动的问题
改动点：逻辑与改为逻辑或
逻辑与需要 deltaX 和 deltaY 都有位移才会更新文本的位置，如果是水平横向或纵向拖拽文本，则不会跟随鼠标移动；而实际上，在拖拽时，只要鼠标在水平或竖直方向有位移，都应该更新文本位置，故改为逻辑或。
=> fix: 修复文本拖拽不符合预期的问题

examples/feature-examples/.umirc.ts, examples/feature-examples/src/pages/grid/index.less, examples/feature-examples/src/pages/grid/index.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/view/Graph.tsx, packages/core/src/view/overlay/Grid.tsx
#1730
- 支持通过 `graphModel.updateGridOptions()` 方法动态修改 Grid 的配置，如控制 Grid 的显隐、大小、类型、宽度和颜色等（详见增加的示例）
- 在 `examples/feature-examples` 中增加动态修改网格配置的示例
=> feat: 支持动态修改 Grid 的配置

scripts/build-less
#1920
这个改动能解决 windows 系统 node20 环境下样式文件打包脚本执行报错的问题，同时不影响 node18 环境下的脚本执行，也不会影响 mac 在 node18 或 node20 下的脚本执行。
=> fix: 修复 windows 系统 node20 环境下样式文件打包失败的问题

examples/feature-examples/src/pages/grid/index.tsx, packages/core/src/view/overlay/Grid.tsx
> #1904 
重写 Grid 的时候没有考虑到原先只有一半的宽度可见，实际表现就是 2.x 的网格在相同的网格线宽下，线的宽度实际上是 1.x 的两倍。举个例子，使用下面的配置，在 1.x 下，网格的线宽实际上是 `stroke-width="0.5"`；而在 2.x 下，网格的线宽实际上是 `stroke-width="1"`。
```js
const gridConfig = {
type: 'mesh',
config: {
thickness: 1
}
}
```
考虑到迁移影响，这里就将 2.x 的表现调整为与 1.x 的表现一致。
=> fix: 修复 2.x 与 1.x 下相同的网格线宽，Grid 表现不一致的问题

packages/core/src/event/eventArgs.ts
前置 PR：#1916
相关 ISSUE 与 PR：#1922 #1923
忘了类型检查问题会直接导致 build 失败，这里补一下😂。
=> fix: 修复 node:dnd-drag 事件的类型检查问题

examples/vue3-app/src/views/LogicFlowView.vue
昨天把项目拉下来想尝试使用vue3自定义组件，但是发现该组件无法正常显示
将 flowId 传递给 TeleportContainer 之后可以修复该问题
=> fix(example): 修复文档中vue3自定义组件不能正常显示bug

examples/feature-examples/src/pages/graph/index.tsx, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/view/edge/BaseEdge.tsx
修复笔记本触摸板点击边事件失效（PR #1497 重新提交）
=> fix(core): 修复笔记本触摸板点击边事件失效

packages/core/src/util/drag.ts, packages/core/src/view/Control.tsx
fix [https://github.com/didi/LogicFlow/issues/1934](https://github.com/didi/LogicFlow/issues/1934)
fix [https://github.com/didi/LogicFlow/issues/1926](https://github.com/didi/LogicFlow/issues/1926)
为了解决`Control`组件意外销毁，但是没有及时释放监听事件的问题，在组件销毁时，强制触发了
```ts
componentWillUnmount() {
this.dragHandler.cancelDrag()
}
```
这导致一个问题
- 用户点击node，会显示出`Control`组件，点击空白地方会隐藏`Control`组件，从而触发`componentWillUnmount`，从而触发cancelDrag()->onDragEnd()->updateEdgePointByAnchors()触发线的重新计算
- 用户经过node，然后离开node，也会触发触发`componentWillUnmount`，从而触发cancelDrag()->onDragEnd()->updateEdgePointByAnchors()触发线的重新计算
自动触发计算逻辑一直存在，但是一般是拖拽时才会触发，用户也能理解这个逻辑
但是目前这个组件销毁时就触发一次自动触发计算会给用户造成一种bug的错觉
我们的本意是为了防止`mousemove`和`mouseup`没有及时被移除，如下面所示，在触发`handleMouseDown`时，会注册监听，在`handleMouseUp`时，会解除监听
```ts
handleMouseDown = (e: MouseEvent) => {
const …
```
=> fix(core): 在没有拖拽的情况下，Control组件突然销毁，不触发cancelDrag(#1926)

packages/core/src/event/eventArgs.ts, packages/extension/src/dynamic-group/model.ts, packages/extension/src/dynamic-group/node.ts, sites/docs/docs/api/eventCenter.en.md, sites/docs/docs/api/eventCenter.zh.md
fix [https://github.com/didi/LogicFlow/issues/1912](https://github.com/didi/LogicFlow/issues/1912)
fix [https://github.com/didi/LogicFlow/issues/1914](https://github.com/didi/LogicFlow/issues/1914)
fix [https://github.com/didi/LogicFlow/issues/1918](https://github.com/didi/LogicFlow/issues/1918)
下面视频展示的关系为：dynamicGroupA嵌套dynamicGroupB，dynamicGroupB嵌套普通Node
由于dynamicGroupA嵌套dynamicGroupB，在dynamicGroupA进行折叠时，会触发dynamicGroupB的隐藏，从而触发dynamicGroupB的`componentWillUnmount()`销毁，但是如下面视频所示，dynamicGroupB的`componentDidMount()`注册了很多事件：
```ts
componentDidMount() {
super.componentDidMount()
const { eventCenter } = this.props.graphModel
// 在 group 旋转时，对组内的所有子节点也进行对应的旋转计算
eventCenter.on('node:rotate', this.onNodeRotate)
// 在 group 缩放时，对组内的所有子节点也进行对应的缩放计算
eventCenter.on('node:resize', this.onNodeResize)
// …
```
=> fix(extension): 【dynamic-group】修复mousemove和isCollapsed相关问题

packages/core/__tests__/algorithm/egde.test.ts, packages/core/src/algorithm/edge.ts
修改了下面这个算法。这个算法只考虑到了endPoint的x,y均比startPoint的x,y大的情况，逻辑不严谨，从而间接导致了polyline与多边形的交点位置与预期不符
https://github.com/didi/LogicFlow/blob/e9f097c1532874c83c14ffefe01215e3be8bb278/packages/core/src/algorithm/edge.ts#L52-L69
详见：https://github.com/didi/LogicFlow/issues/1945#issuecomment-2456765882
=> fix(core): 修复 polyline 与多边形节点的交点不正确的问题

packages/core/__tests__/algorithm/egde.test.ts, packages/core/src/algorithm/edge.ts
上个pr漏改了: https://github.com/didi/LogicFlow/pull/1947#issue-2635191196
https://github.com/didi/LogicFlow/blob/e9f097c1532874c83c14ffefe01215e3be8bb278/packages/core/src/algorithm/edge.ts#L67
其中 `y - k * x + b` 应该改成 `y - k * x - b`
=> fix(core): 修复因算法错误导致 polyline 与多边形节点的交点不正确的问题

examples/feature-examples/src/pages/edges/custom/animate-polyline/index.tsx, packages/extension/src/materials/group/GroupNode.ts, packages/extension/src/materials/group/index.ts, sites/docs/docs/tutorial/extension/node-resize.en.md, sites/docs/docs/tutorial/extension/node-resize.zh.md, sites/docs/docs/tutorial/update.zh.md, sites/docs/examples/edge/custom/demo/animatePolyline.tsx, sites/docs/examples/edge/custom/demo/meta.json
=> fix(extension): group插件isAllowMoveTo方法的参数名优化

packages/core/src/event/eventArgs.ts, packages/core/src/model/GraphModel.ts, packages/extension/src/dynamic-group/index.ts
DynamicGroup 的 removeNodeFromGroup 方法判断是否是分组节点需要从 model 里获取，data 里没有 isGroup 属性，导致删除子节点的代码无效。
修改为在删除节点触发事件时额外传递 model 参数，用 model 的 isGroup 进行判断。
原行为：
修改后：
之前 DynamicGroup getGroupByBounds 中缺失 zIndex 的判断逻辑
参考旧的 Group 组件的 getGroup 方法中的处理添加了对 zIndex 的判断
原行为：
修改后：
=> 修复 DynamicGroup 相关 bug

examples/engine-browser-examples/src/pages/extension/label/index.tsx, packages/core/src/LogicFlow.tsx, packages/core/src/view/node/BaseNode.tsx, packages/extension/src/style/index.less, packages/extension/src/style/raw.ts, packages/extension/src/tools/label/Label.tsx, packages/extension/src/tools/label/LabelModel.ts, packages/extension/src/tools/label/index.ts
feat:
1.  label支持删除
2. 点击其他label时，当前获焦label失焦
fix: 
1. 修复文本框固定展示白底和hover后内容偏移问题
2. 修复Label框单击后无法拖动问题
3. 修复拖拽面板被label遮挡问题
4. 修复使用label的情况下双击节点会让节点进入编辑态
relate issues #1966 #1910 #1909
=> fix: 修复一系列Label插件问题

packages/core/src/algorithm/outline.ts, packages/core/src/constant/index.ts, packages/core/src/event/eventArgs.ts, packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/LineEdgeModel.ts, packages/core/src/model/edge/PolylineEdgeModel.ts, packages/core/src/style/index.less, packages/core/src/style/raw.ts, packages/core/src/view/edge/BaseEdge.tsx, packages/core/src/view/node/BaseNode.tsx, packages/core/src/view/overlay/OutlineOverlay.tsx
=> fix(core): 修复issue反馈的问题

sites/docs/examples/showcase/bussiness/demo/meta.json
增加一个业务场景示例——基于 LogicFlow 实现的[仪器配置文件编辑器](https://instrument-profile-editor.hisoten.xyz/)。
该项目用于支持仪器配置文件的图形化编辑，在该业务场景下，配置文件的嵌套层级固定为四层，非常适合用类似脑图的编辑方式来支持图形化编辑。
=> feat: 增加业务场景示例

examples/feature-examples/src/pages/graph/index.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/view/Graph.tsx
=> fix: 兼容不设置高度时,窗口变化后更新画布尺寸

examples/feature-examples/src/pages/graph/index.tsx, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/model/node/BaseNodeModel.ts
- 初始化节点、边时，draggable 和 editable 属性由默认值更新为使用 editConfigModel 中的值
=> fix: 修复设置 textDraggable 为 true 时，边、节点文本无法拖拽的 bug

sites/docs/docs/tutorial/basic/class.en.md, sites/docs/docs/tutorial/basic/class.zh.md
在使用 LogicFlow时，我发现基础教程中的实例文档中，关于节点和边的属性链接存在跳转失败的问题。 [地址](https://site.logic-flow.cn/tutorial/basic/class)
=> fix(docs): 修复文档中“基础教程”和“实例”部分的 `nodeModel` 和 `edgeModel` 跳转地址错误

examples/feature-examples/src/pages/edges/custom/polyline/index.tsx, examples/feature-examples/src/pages/graph/index.tsx, packages/core/src/LogicFlow.tsx, packages/core/src/model/EditConfigModel.ts, packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/PolylineEdgeModel.ts, packages/core/src/util/geometry.ts, packages/core/src/view/behavior/dnd.ts, packages/core/src/view/node/BaseNode.tsx, packages/core/src/view/overlay/CanvasOverlay.tsx
=> fix(core): 网格对齐改为开关控制 & 修复初始化时流程图偏移问题

examples/engine-browser-examples/src/pages/extension/dynamic-group/index.tsx, packages/extension/src/components/selection-select/index.ts, packages/extension/src/dynamic-group/model.ts, packages/extension/src/dynamic-group/node.ts
在 https://github.com/didi/LogicFlow/pull/1858 中，分组内节点跟随移动的逻辑被放在了 node:mousemove 事件监听中，导致只有拖拽才会触发该逻辑。对分组使用 Api 如 moveNode 时，不会触发这个事件，子节点不跟随。
现将跟随移到逻辑改到 getMoveDistance 中，拖拽和使用方法进行移动时均会执行该方法。
同时，selection-select 插件中有问题，在选择到分组节点时，会将子节点也选中，导致在做了上面的修改后，子节点会移动 n 次。
selection-select 的代码里有对分组情况的处理：
```JavaScript
// 如果节点属于分组，则不选中节点，此处兼容旧版 Group 插件
if (!group || !group.getNodeGroup(element.id)) {
this.lf.selectElementById(element.id, true)
}
// 如果节点属于动态分组，则不不选中节点
if (!dynamicGroup || !dynamicGroup.getGroupByNodeId(element.id)) {
this.lf.selectElementById(element.id, true)
}
```
这样的判断在单独使用分组插件时，会有另一个 if 触发，选中节点。现在修复了该逻辑，不会影响到分组的移动
效果：
这样处理后也能修复 #1949  ，这种场景下，鼠标没有移动，所以不触发事件
效果：
=> fix(extension): 【dynamic-group】DynamicGroup 使用 moveNode 进行移动时子节点没有跟随移动 

packages/core/src/util/node.ts
isInNodeBbox 没处理旋转的场景，用的是旋转前的 bBox 进行判断。现将用于判断的点反向旋转后再进行判断
另外 `isInNode` 和 `isInNodeBbox` 只有 offset 不同，合并了两个方法
close #1871
before: 
after:
=> fix(core): 修复节点旋转后锚点无法被接线的问题

packages/extension/src/style/index.less
close #2017 
> 目前这个 bug 可以直接在 [MiniMap Demo](https://site.logic-flow.cn/examples/extension/native#miniMap) 上复现（可能需要较大幅度的拖动小地图元素来触发）。
基于父元素实际大小调整 LF 画布大小的操作与 MiniMap 的实现有冲突，这里强制覆盖了一下样式，不会对其他功能有影响。
=> fix: 修复调整窗口大小后，小地图插件表现异常的问题

packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/view/node/BaseNode.tsx
多选时的移动未更新 transform 导致旋转的节点位置异常。改成在 getMoveDistance 方法中更新 transform，统一处理所有移动逻辑
before:
after:
=> fix(core): 修复多选旋转的节点后进行移动时，节点位置异常问题

examples/engine-browser-examples/src/pages/extension/dynamic-group/index.tsx, packages/core/src/LogicFlow.tsx, packages/extension/src/dynamic-group/index.ts, packages/extension/src/dynamic-group/model.ts
通过 addChild 添加的节点没有在 nodeGroupMap 中建立映射关系，导致相关逻辑异常。改为在 addChild触发的事件中建立映射
close #2041 #2042
=> fix(extension): dynamic-group 的 addChild 没有处理 nodeGroupMap

sites/docs/docs/article/lowcode-with-logicflow.zh.md, sites/docs/docs/tutorial/get-started.zh.md
在使用 LogicFlow时，我发现基础教程中的实例文档中存在着一些问题
=> fix(docs): 修复文档中快速上手vue示例及相关文章错别字

packages/core/src/view/Control.tsx
当未选中节点时，节点的ResizeControl只有在hover时才启用，当快速缩放时，节点的大小可能会跟不上鼠标导致不在hover状态，组件被卸载，从而退出缩放
修改为在onDragStart时，自动选中节点，使组件不被卸载
close #2085
=> 修复未选中节点时进行快速缩放会退出缩放

packages/core/src/view/Graph.tsx, packages/core/src/view/overlay/ToolOverlay.tsx, packages/extension/src/components/selection-select/index.ts, packages/extension/src/dynamic-group/index.ts
1. 多选节点时可以拖入/拖出分组来加入/离开分组
相关issue: #2073
2. 修改框选插件的实现方式，允许在分组内部进行框选
效果：
=> 优化多选、框选与分组插件的联动

packages/react-node-registry/src/model.ts
删除了 react model 中 setAttributes 时打印的 this.properties
需要可以自行打印，打印太多污染控制台了
=> fix: delete console.log

sites/docs/docs/api/theme.en.md, sites/docs/docs/api/theme.zh.md
=> fix(docs): 文档api主题anchorLine描述错误问题

examples/feature-examples/src/pages/extensions/highlight/index.tsx, packages/extension/src/components/highlight/index.ts, packages/extension/src/dynamic-group/index.ts, packages/extension/src/tools/proximity-connect/index.ts, packages/react-node-registry/src/view.ts, sites/docs/docs/api/eventCenter.en.md, sites/docs/docs/api/eventCenter.zh.md
=> 5.6~5.9 issue fix round 1

examples/feature-examples/src/pages/extensions/selection-select/index.tsx, packages/core/src/model/GraphModel.ts
- 问题原因，复制粘贴后，新边的 sourceAnchorId 和 targetAnchorId 没有更新，导致开始调整时代码就报错。
=> fix: 修复批量框选后，调整边起终点报错的 bug。

packages/core/src/LogicFlow.tsx, packages/core/src/model/SnaplineModel.ts, packages/core/src/options.ts
This PR have not passed the test, because of some unrelated errors.
And the jest systax error: jest-runner\build\index.js: Class private methods are not enabled
=> fix(snapline): snapline cannot show when zoomed
