didi/LogicFlow

docs/guide/advance/theme.md, packages/core/src/constant/DefaultTheme.ts, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/view/overlay/OutlineOverlay.tsx
1. Add stroke-dasharray vlaue to outline of node & edge
2. This close #12
=> feat(core): Add stroke-dasharray vlaue to outline of node & edge

packages/core/src/constant/constant.ts, packages/core/src/view/Anchor.tsx, packages/site/src/app.tsx
=> feat(core): support open text edit by double click anchor

docs/guide/extension/extension-components.md, examples/src/pages/extension/adapter/index.tsx, examples/src/pages/extension/components/dnd-panel/index.tsx, examples/src/routes.tsx, packages/core/src/view/Graph.tsx, packages/extension/scripts/webpack.config.base.js, packages/extension/src/components/dnd-panel/index.ts, packages/extension/src/index.ts, packages/site/src/app.tsx
1. move the tool overlay out of the graph. fix #16 
2. change the name of DND component
=> fix(core): move the tool overlay out of the graph

docs/guide/advance/event.md, packages/site/src/utils/addListener.ts
add event type：
- `node:mouseenter`
- `node:mouseleave`
- `edge:mouseenter`
- `edge:mouseleave`
close #15
=> docs: complete event doc

examples/src/pages/usage/bpmn/index.tsx, examples/src/pages/usage/bpmn/io.tsx, packages/core/src/view/Graph.tsx, packages/core/src/view/overlay/CanvasOverlay.tsx
1. fix(core): fix textEdit deviation
2. feat(examples): add download image to bpmn
=> fix(core): fix textEdit deviation

docs/api/logicFlowApi.md, docs/guide/advance/event.md, docs/guide/advance/theme.md, packages/core/src/LogicFlow.tsx, packages/core/src/constant/DefaultTheme.ts, packages/core/src/model/node/CircleNodeModel.ts, packages/core/src/model/node/DiamondNodeModel.ts, packages/core/src/model/node/EllipseNodeModel.ts, packages/core/src/view/node/EllipseNode.tsx
1. optimize anchor selection
2. add getPointByClient API
3. recovery ellipse size
close #22
=> fix(core): optimize anchor selection

docs/guide/advance/event.md, packages/core/src/LogicFlow.tsx, packages/core/src/event/event.md, packages/core/src/model/GraphModel.ts, packages/core/src/view/behavior/DnD.ts, packages/core/src/view/edge/BaseEdge.tsx, packages/core/src/view/node/BaseNode.tsx, packages/core/src/view/overlay/CanvasOverlay.tsx, packages/extension/src/components/menu/index.ts, packages/site/src/utils/addListener.ts
- change the priority of events
- fix the typos and parameter type of getPointByClient API
=> fix(core): change the priority of events

developer.md, docs/guide/extension/extension-components.md, packages/core/index.html, packages/core/src/tool/TextEditTool.tsx, packages/core/src/view/edge/BaseEdge.tsx, packages/extension/src/components/menu/index.ts
1. fix error when double click edge
2. add changeMenuItem API
3. add developer.md for publish
=> Add changeMenuItem API & bugfix

packages/extension/examples/bpmn/index.html, packages/extension/examples/bpmn/index.js, packages/extension/src/adapter/index.ts
json2xml not support undefined property
=> fix(extension): 🐛 fix bpmn demo download not work

README.md
feat(docs): Add introduction of logicflow-vue-demo in README
fix(docs):  update the gif of logicflow_vue_demo in README
=> feat(docs): Add introduction of logicflow-vue-demo in README

docs/guide/extension/extension-components.md
fix invalid import path for #2
=> fix: invalid import path

packages/core/src/constant/constant.ts, packages/core/src/model/edge/PolylineEdgeModel.ts, packages/core/src/model/node/DiamondNodeModel.ts, packages/core/src/type/index.ts
- fix: lack the outline style of edge
- fix: the render err of diamond
=> fix: 🐛 lack the outline style of edge

docs/guide/advance/theme.md
=> docs: 修改文档错误

packages/core/src/LogicFlow.tsx, packages/core/src/keyboard/shortcut.ts
=> fix: 🐛 beforeClone is not be triggered by ctrl+v

packages/core/src/LogicFlow.tsx
=> refactor: arrange LogicFlow.tsx

packages/core/index.html, packages/core/src/LogicFlow.tsx, packages/core/src/model/BaseModel.ts, packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/view/node/CircleNode.tsx, packages/core/src/view/node/EllipseNode.tsx, packages/core/src/view/node/PolygonNode.tsx, packages/core/src/view/node/RectNode.tsx
=> feat: add updateAttributes API

packages/extension/scripts/webpack.config.dev.js
=> chore: disable eslint plugin in webpack dev

packages/extension/src/style/index.css
fix Gradient has outdated direction syntax
issues：https://github.com/postcss/autoprefixer/issues/530
=> fix: Gradient has outdated direction syntax

docs/guide/extension/bpmn-element.md
fix bpmn-element.md warn about props type
=> docs: fix bpmn-element.md warn

examples/src/pages/extension/components/custom-dnd/DndTool.tsx, examples/src/pages/usage/approve/components/NodePanel.tsx, examples/src/pages/usage/approvePreview/index.tsx
The panel moves with the mouse position
=> perf: add mousemove in examples

packages/core/index.html, packages/core/scripts/webpack.config.dev.js, packages/core/src/LogicFlow.tsx, packages/core/src/index.tsx, packages/core/src/view/behavior/DnD.ts, packages/core/src/view/edge/index.ts, packages/core/src/view/index.ts, packages/core/src/view/node/CircleNode.tsx, packages/core/src/view/node/PolygonNode.tsx, packages/core/src/view/node/RectNode.tsx, packages/core/src/view/node/index.ts, packages/core/src/view/overlay/OutlineOverlay.tsx
=> refactor: rewrite register API

package.json, packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/options.ts, yarn.lock
affects: @logicflow/core
- add createId API in element model
- add idGenerator global option
- add commitizen tool
resolve #199
=> feat: add createId API

packages/core/src/LogicFlow.tsx
=> fix: 修复getSelectElements方法,即使选中元素,但是依然返回为undefined的bug

packages/core/src/model/GraphModel.ts
需不需要加入这个API，大佬们帮忙评估下。
相对位置移动的使用方式：
```javascript
// 相对于当前节点50，的当前位置，x轴移动100，y轴移动100
lf.graphModel.moveNode(50, 100, 100);
```
新增移动到画布（100,100）的API能力：
```javascript
//  移动节点50，到画布的x轴100，y轴100
lf.graphModel. moveNode2Coordinate(50, 100, 100);
```
=> feat: 新增move节点采用绝对位置,修复移动边,节点id类型不一致(数字和字符串)导致边不跟随移动的bug

packages/core/index.html, packages/extension/examples/NodeResize/index.html, packages/extension/examples/bpmn/index.html, packages/extension/examples/components/SelectionSelect/index.html, packages/extension/examples/components/minimap/index.html, packages/extension/examples/destroy.html, packages/extension/examples/ie/index.html, packages/extension/examples/insert-node-in-polyline/index.html, packages/extension/examples/materials/curved-edge/index.html, packages/extension/examples/rect-label-node/index.html, packages/extension/examples/rules/index.html, packages/extension/examples/snapshot/index.html
=> fix(examples): modified examples page title

docs/guide/extension/component-dnd-panel.md, packages/extension/src/components/dnd-panel/index.ts
=> fix(extension): revise typo

docs/guide/advance/customEdge.md
=> 修复文档中属性写错问题

examples/src/App.css, examples/src/App.tsx, examples/src/constants/index.ts
=> feat: :sparkles: example新增导航

docs/guide/basic/node.md
=> fix: 修改描述错误

packages/core/scripts/webpack.config.dev.js, packages/core/src/view/node/PolygonNode.tsx, packages/extension/examples/materials/node-selection/index.html, packages/extension/examples/materials/node-selection/index.js, packages/extension/scripts/webpack.config.base.js, packages/extension/scripts/webpack.config.dev.js, packages/extension/src/index.ts, packages/extension/src/materials/node-selection/index.ts
=> add node-selection plugin

packages/extension/src/materials/node-selection/index.ts
fix: fix addNodeSelection methods in node-selection plugin
=> fix: fix addNodeSelection methods in node-selection plugin

packages/extension/examples/materials/node-selection/index.js, packages/extension/src/materials/node-selection/index.ts
-  add disableNodeSelection callback in node-selection
- dd disabled_delete attr in node-selection
=> modify node-selection plugin

docs/api/edgeModelApi.md, docs/api/graphModelApi.md, docs/api/logicFlowApi.md, packages/core/examples/animation/customBezier.mjs, packages/core/examples/animation/index.html, packages/core/examples/animation/index.mjs, packages/core/src/constant/DefaultAnimation.ts, packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/options.ts, packages/core/src/style/index.css, packages/core/src/util/animation.ts, packages/core/src/view/edge/BaseEdge.tsx, packages/core/src/view/edge/BezierEdge.tsx, packages/core/src/view/edge/LineEdge.tsx, packages/core/src/view/edge/PolylineEdge.tsx
=> feat: support animation

packages/extension/src/tools/auto-layout/index.ts
当旧trunk和新trunk长度一致时，用于选择旧trunk,
```
a->b->c->d
|->e
```
`e` 后面新增 `f` 节点时候，旧逻辑会返回新trunk `[a,b,e,f]`，界面布局变成
```
a->b->e->f
|->c->d
```
其实只想要这样 尽量少变化
```
a->b->c->d
|->e->f
```
=> perf: 优化layout trunk

packages/core/src/LogicFlow.tsx, packages/core/src/model/GraphModel.ts
支持画布整体移动到画布中心，提供新的api: lf.translateCenter()
=> feat: 支持画布整体居中

packages/core/index.html, packages/core/src/LogicFlow.tsx, packages/core/src/model/GraphModel.ts
=> feat: 画布居中代码优化

packages/core/index.html, packages/core/src/LogicFlow.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/type/index.ts
=> feat: 优化画布图形居中虚拟矩形的计算规则，新增适应屏幕大小功能

packages/core/src/LogicFlow.tsx, packages/extension/examples/locale/index.html, packages/extension/examples/locale/index.js, packages/extension/scripts/webpack.config.base.js, packages/extension/src/components/control/index.ts, packages/extension/src/components/menu/index.ts, packages/extension/src/index.ts, packages/extension/src/locale/en-locale/en.ts, packages/extension/src/locale/en-locale/index.ts, packages/extension/src/locale/locale.ts
PR #580, moved to `v1.2.0` branch
=> feat: english locale extension

packages/extension/src/components/control/index.ts
我测试了英文下的控制板和菜单。发现Undo/Redo这里应做修改。 #580 #582
=> Fix control undo/redo item in EnLocale

docs/guide/basic/edge.md
新增基于React组件自定义连线的方式及对应示例的CodeSandBox链接
=> docs: 新增基于React组件自定义连线的方式

packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/view/edge/BaseEdge.tsx, packages/core/src/view/node/HtmlNode.tsx, packages/extension/examples/highlight/index.html, packages/extension/examples/highlight/index.mjs, packages/extension/scripts/webpack.config.base.js, packages/extension/src/components/highlight/index.ts, packages/extension/src/index.ts
修复edge事件mouseenter触发多次的问题
添加高亮聚焦插件，基于svg opacity属性
=> feat: add highlight plugin & fix: edge:mouseenter trigger twice

packages/core/index.js, packages/core/package.json, packages/core/scripts/webpack.config.build.js
affects: @logicflow/core
ISSUES CLOSED: #561
=> chore: provide uncompression build file for development environment

examples/README.md
=> fix: 🐛 examples readme

docs/guide/basic/node.md
=> docs: 修正文档中关于 sourceRules、targetRules 的使用示例

packages/core/src/model/edge/BaseEdgeModel.ts
修复https://github.com/didi/LogicFlow/issues/944#issue-1497973900
=> fix: getEndAnchor

packages/extension/src/materials/curved-edge/index.ts, packages/extension/src/materials/curved-edge/searchMiddleIndex.ts
https://github.com/didi/LogicFlow/issues/952#issue-1502726421
=> fix: issues890

packages/core/src/LogicFlow.tsx
=> 🐞 fix(core): 修复对render函数的注释内容存在的拼写错误

packages/core/src/model/edge/BaseEdgeModel.ts
https://github.com/didi/LogicFlow/issues/957
=> fix:getBeginAnchor

packages/core/src/view/edge/AdjustPoint.tsx
https://github.com/didi/LogicFlow/issues/950
=> 调整边连接的节点时如果还是连接到之前的节点上的同一个锚点则还原边且不emit edge:exchange-node事件

packages/core/src/view/edge/AdjustPoint.tsx
https://github.com/didi/LogicFlow/issues/982
=> Fixes AdjustPointDraging

packages/extension/src/components/selection-select/index.ts
修复 https://github.com/didi/LogicFlow/issues/985 问题
=> 禁用画布右键框选功能修复可能会导致画布存在多个框选框不会消失的问题

packages/core/src/view/edge/AdjustPoint.tsx
https://github.com/didi/LogicFlow/issues/974
=> fix #974: 在拖拽AdjustPoint时不修改edgeModel.isHitable避免可能出现边不能点击问题

packages/extension/src/tools/snapshot/index.ts
=> fix: export images compatible with Firefox(#269)

packages/extension/__test__/bpmn-adapter.test.js, packages/extension/src/bpmn-adapter/index.ts, packages/extension/src/bpmn-adapter/json2xml.ts, packages/extension/src/bpmn-adapter/xml2json.ts
1.  fix the bug of cdata-transformation in extension: bpmn-adapter
2. add node type reference
3. support #comment parsing
=> fix the bug of cdata-transformation in extension: bpmn-adapter

jest.config.js, package.json, packages/extension/__test__/bpmn-adapter.test.js, packages/extension/src/bpmn-adapter/index.ts, packages/extension/src/bpmn-adapter/json2xml.ts, packages/extension/src/bpmn-adapter/xml2json.ts
修复xml与json互相转换中出现的一些问题，后续需要对文档进行修改
=> fix execution bug in xml ⇄ json

packages/core/src/util/edge.ts
close [https://github.com/didi/LogicFlow/issues/817](https://github.com/didi/LogicFlow/issues/817)
close [https://github.com/didi/LogicFlow/issues/1042](https://github.com/didi/LogicFlow/issues/1042)
使用了`expendBBox`的宽度和高度进行直角折线的第一个点（startPos的下一个点）的方向计算，导致`pointDirection()`拿到的方向错误，如下面图片所示，下面一个矩形计算出来的方向是`HORIZONTAL`
```js
export const pointDirection = (point: PolyPoint, bbox: PBBox): Direction => {
const dx = Math.abs(point.x - bbox.centerX);
const dy = Math.abs(point.y - bbox.centerY);
return dx / bbox.width > dy / bbox.height
? SegmentDirection.HORIZONTAL
: SegmentDirection.VERTICAL;
};
export const getExpandedBBoxPoint = (
bbox: PBBox,
point: PolyPoint,
): PolyPoint => {
const direction = pointDirection(point, bbox);
if (direction === SegmentDirection.HORIZONTAL) {
return {
x: point.x > …
```
=> fix(core): compute the first point direction of the rectangular polyline using the original width and height(#817)

packages/core/src/model/GraphModel.ts
close [https://github.com/didi/LogicFlow/issues/1191](https://github.com/didi/LogicFlow/issues/1191)
经过排查，在1.2.4->1.2.5版本的提交中，某一个提交导致了`自定义连线上的text位置不跟随连线Edge偏移， 跟随的是节点Node偏移`的问题，具体提交为：`feat: support move selected nodes when disabled multipleSelect.(#894) 2023/5/3 at 19:28`
进行深度排查后发现，之所以`moveNode()`->`moveNodes()`会导致`自定义连线上的text位置不跟随连线Edge偏移， 跟随的是节点Node偏移`的问题是因为两个方法里面的逻辑没有统一
具体为`moveNode()`处理边上文字时，会触发
```js
// 如果是自定义边文本位置，则移动节点的时候重新计算其位置
if (edgeModel.customTextPosition === true) {
edgeModel.resetTextPosition();
} else if (edgeModel.modelType === ModelType.POLYLINE_EDGE && edgeModel.text?.value) {
const textPosition = edgeModel.text;
const newPoint = getClosestPointOfPolyline(textPosition, edgeModel.points);
edgeModel.moveText(newPoint.x - textPosition.x, newPoint.y - textPosition.y);
} …
```
=> fix(core): moveNodes() add the logic of the moveNode function to calculate the moving distance of the side text

packages/extension/src/NodeResize/Control/Control.tsx
close [https://github.com/didi/LogicFlow/issues/807](https://github.com/didi/LogicFlow/issues/807)
close [https://github.com/didi/LogicFlow/issues/875](https://github.com/didi/LogicFlow/issues/875)
之前的做法，比如Rect是使用getRectResizeEdgePoint()计算边的point缩放后的位置
getRectResizeEdgePoint()考虑了瞄点在四条边以及在4个圆角的情况
使用的是一种等比例缩放的模式，比如：
```js
onDragging = ({ deltaX, deltaY }) => {
if (modelType === ModelType.RECT_NODE || modelType === ModelType.HTML_NODE) {
this.updateRect({ deltaX, deltaY });
}
}
updateRect = ({ deltaX, deltaY }) => {
// 更新边
let afterPoint;
edges.sourceEdges.forEach(item => {
params.point = item.startPoint;
afterPoint = getRectResizeEdgePoint(params);
item.updateStartPoint(afterPoint);
});
}
function getRectResizeEdgePoint({ point, beforeNode, afterNode }) {
//...
if (x === beforeNodeBox.maxX) …
```
=> fix: use anchors to adjust the pos of edges during dragging(#807#875)

packages/extension/src/components/menu/index.ts
close [https://github.com/didi/LogicFlow/issues/1019](https://github.com/didi/LogicFlow/issues/1019)
默认为`top`和`left`，没有考虑边界情况
1. 先使用浏览器窗口可视区域减去目前触摸点的位置，得到一个`distance`
2. 判断目前画布是否充满浏览器窗口可视区域，如果没有充满，应该使用目前画布区域减去目前触摸点的位置，更新`distance`
3. 判断`distance`是否能够满足`menuWidth`/`menuHeight`
4. 如果不能满足，则适配`top`和`left`，让`left = x - width`以及`top = y - height`
=> fix: calculate the pos of the menu considering the bounds(#1019)

dev.sh, packages/core/src/LogicFlow.tsx, packages/core/src/type/index.ts, packages/extension/src/bpmn-elements-adapter/index.ts, packages/extension/src/bpmn-elements-adapter/json2xml.ts, packages/extension/src/bpmn-elements/index.ts, packages/extension/src/bpmn-elements/presets/Event/EndEventFactory.ts, packages/extension/src/bpmn-elements/presets/Event/IntermediateCatchEvent.ts, packages/extension/src/bpmn-elements/presets/Event/IntermediateThrowEvent.ts, packages/extension/src/bpmn-elements/presets/Event/StartEventFactory.ts, packages/extension/src/bpmn-elements/presets/Event/boundaryEventFactory.ts, packages/extension/src/bpmn-elements/presets/Flow/sequenceFlow.ts, packages/extension/src/bpmn-elements/presets/Gateway/gateway.ts, packages/extension/src/bpmn-elements/presets/Task/index.ts, packages/extension/src/bpmn-elements/presets/Task/subProcess.ts, packages/extension/src/bpmn-elements/presets/Task/task.ts, packages/extension/src/bpmn-elements/utils.ts, packages/extension/src/bpmn/getBpmnId.ts
1、优化BPMNAdapter
2、LogicFlow.use新增插件入参
=> feat: optimize BPMNAdapter; add input props when register plugin

packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/type/index.ts, packages/core/src/util/index.ts, packages/core/src/view/node/BaseNode.tsx
1. Export edge utils and sampling utils. #825 
2. Add a new function `getOuterGAttributes` to set the outer g tag's attributes.  #880
=> feat(core): add a new function to set outer g tag's attributes

examples/src/pages/basic/edge/index.tsx, packages/core/src/constant/DefaultTheme.ts, packages/core/src/constant/constant.ts, packages/core/src/model/EditConfigModel.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/style/index.css, packages/core/src/type/index.ts, packages/core/src/util/index.ts, packages/core/src/util/matrix.ts, packages/core/src/util/vector.ts, packages/core/src/view/Rotate.tsx, packages/core/src/view/node/BaseNode.tsx, packages/core/src/view/overlay/BezierAdjustOverlay.tsx, packages/core/src/view/overlay/OutlineOverlay.tsx, packages/extension/src/tools/snapshot/index.ts
fix:
1. Trigger edge:adjust when adjusting bezier(#947)
feat:
1. Enable node rotation (#1298 #390 )
todo:
1. Need to update documents about rotation before the next release
=> feat(core): enable node rotation

packages/extension/src/materials/group/GroupNode.ts
=>  add group:remove-node and group:add-node event(#800)

packages/core/index.html, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/util/node.ts, packages/core/src/view/Rotate.tsx, packages/core/src/view/node/BaseNode.tsx, packages/core/src/view/overlay/OutlineOverlay.tsx
=> fix(core): restore rotation

packages/core/index.html, packages/core/src/constant/DefaultTheme.ts, packages/core/src/tool/TextEditTool.tsx, packages/core/src/type/index.ts, packages/core/src/view/Anchor.tsx, packages/core/src/view/edge/AdjustPoint.tsx, packages/core/src/view/edge/BaseEdge.tsx, packages/core/src/view/node/BaseNode.tsx
fix #1365 
fix #1395 
resolve #1390
=> fix(core): anchorId missed after point adjusting(#1365)

README.md, README.zh-cn.md, packages/core/src/tool/TextEditTool.tsx, packages/core/src/util/drag.ts, packages/extension/src/components/mini-map/index.ts
fix #1419 
fix #1432 
fix #1433
=> 修复若干 bug，README 新增图书推荐内容

docs/api/graphModelApi.md
=> fix: 更新文档拼写错误

packages/core/src/LogicFlow.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/model/edge/BezierEdgeModel.ts, packages/core/src/model/edge/PolylineEdgeModel.ts, packages/core/src/view/Anchor.tsx, packages/extension/src/tools/snapshot/index.ts
close #1449 
close #1472 
close #1526
=> fix: 修复锚点相关问题&导出插件相关问题

packages/core/src/util/browser.ts, packages/core/src/view/Anchor.tsx
=> fix：锚点连线失败增加默认错误提示 & 修复没有window对象情况下判断浏览器环境报错问题

packages/core/src/options.ts
修复[issue#1565](https://github.com/didi/LogicFlow/issues/1565)
=> fix:修复grid颜色样式被覆盖问题

examples/CHANGELOG.md, examples/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/extension/CHANGELOG.md, packages/extension/package-lock.json, packages/extension/package.json
- examples@1.2.14
- @logicflow/core@1.2.27
- @logicflow/extension@1.2.27
=> Add 1.2.27 publish info

examples/feature-examples/src/pages/extensions/mini-map/index.less, examples/feature-examples/src/pages/extensions/mini-map/index.tsx, packages/core/src/LogicFlow.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/model/node/BaseNodeModel.ts, packages/core/src/view/Rotate.tsx, packages/core/src/view/behavior/DnD.ts, packages/core/src/view/edge/AdjustPoint.tsx, packages/extension/src/bpmn-elements/presets/Pool/Lane.ts, packages/extension/src/bpmn-elements/presets/Task/subProcess.ts, packages/extension/src/components/control/index.ts, packages/extension/src/components/mini-map/index.ts, packages/extension/src/materials/group/GroupNode.ts, packages/extension/src/materials/group/index.ts
- core包与extension包部分类型定义完善
- MiniMap插件功能丰富与相关示例内容丰富
- 小地图中可选择是否渲染连线，支持初始化时设置或通过`setShowEdge`方法更新设置
- 更完善的代码注释与类型定义
- 现在，小地图默认将位于画布的右下角，保留`show`方法设置画布位置的功能，新增`updatePosition`方法用于更新小地图相对画布的决定定位
- 在小地图等示例中增加了新增功能的演示（连线可选渲染与位置调整）
=> feat: 部分类型定义完善与MiniMap插件功能丰富

README.md
=> chore(README.md): Update README.md

packages/core/src/LogicFlow.tsx, packages/core/src/event/event.md, packages/core/src/event/eventArgs.ts, packages/core/src/event/eventEmitter.ts, packages/core/src/model/TransformModel.ts, packages/core/src/tool/TextEditTool.tsx, packages/core/src/view/Anchor.tsx, packages/core/src/view/node/BaseNode.tsx, packages/extension/src/materials/group/index.ts
=> refactor: 事件系统的类型定义完善

examples/feature-examples/src/pages/extensions/bpmn/index.tsx, examples/feature-examples/src/pages/extensions/mini-map/index.tsx, packages/core/src/LogicFlow.tsx, packages/core/src/options.ts, packages/extension/src/bpmn/constant.ts, packages/extension/src/bpmn/index.ts, packages/extension/src/components/control/index.ts, packages/extension/src/components/mini-map/index.ts, packages/extension/src/components/selection-select/index.ts, packages/extension/src/materials/group/index.ts
- 解决插件中一些类型问题
- 测试并修复 LogicFlow.use api 的功能 bug
=> feat(core): 更新插件相关类型定义，完善插件相关方法 use/installPlugins/installPlugin 的功能

sites/docs/docs/tutorial/getting-started.en-US.md, sites/docs/docs/tutorial/getting-started.md, sites/docs/src/tutorial/getting-started/use-in-react/index.jsx
=> fix: 修复官网demo报错

examples/feature-examples/src/pages/extensions/menu/index.tsx, packages/core/src/model/GraphModel.ts, packages/extension/src/components/menu/index.ts, sites/docs/docs/tutorial/extension-component-menu.en-US.md, sites/docs/docs/tutorial/extension-component-menu.md
- 修复初始化时 edgeConfig 中 type 未传值场景下，未使用 graphModel.edgeType(默认边类型) 初始化边的 bug
=> fix(extension): 修复线的 menu 无法正常显示的 bug

packages/core/src/view/overlay/CanvasOverlay.tsx
=> feat(core): 支持cmd + 鼠标滚动操作放大缩小画布

sites/docs/docs/api/detail/index.en.md, sites/docs/docs/api/detail/index.zh.md, sites/docs/docs/api/eventCenter.en.md, sites/docs/docs/api/eventCenter.zh.md, sites/docs/docs/api/index.en.md, sites/docs/docs/api/index.zh.md, sites/docs/docs/api/model/edgeModel.en.md, sites/docs/docs/api/model/edgeModel.zh.md, sites/docs/docs/api/model/graphModel.en.md, sites/docs/docs/api/model/graphModel.zh.md, sites/docs/docs/api/model/nodeModel.en.md, sites/docs/docs/api/model/nodeModel.zh.md, sites/docs/docs/api/theme.en.md, sites/docs/docs/api/theme.zh.md, sites/docs/docs/article/architecture-of-logicflow.en.md, sites/docs/docs/article/architecture-of-logicflow.zh.md, sites/docs/docs/article/decoding-logicflows-extension-mechanism.en.md, sites/docs/docs/article/decoding-logicflows-extension-mechanism.zh.md, sites/docs/docs/article/logicflow-edge-drawing-and-interaction.en.md, sites/docs/docs/article/logicflow-edge-drawing-and-interaction.zh.md, sites/docs/docs/article/logicflow-release-v1.en.md, sites/docs/docs/article/logicflow-release-v1.zh.md, sites/docs/docs/article/lowcode-with-logicflow.en.md, sites/docs/docs/article/lowcode-with-logicflow.zh.md, sites/docs/docs/article/node-resize.en.md, sites/docs/docs/article/node-resize.zh.md
=> fix(site): 官网 API、文章模块修复链接跳转错误和细节优化

sites/docs/.dumirc.ts
=> feat(site): 官网添加百度埋点统计

packages/core/src/view/Graph.tsx, packages/extension/src/tools/snapshot/index.ts, sites/docs/.dumirc.ts, sites/docs/docs/article/extension/snapshot.en.md, sites/docs/docs/article/extension/snapshot.zh.md, sites/docs/docs/tutorial/extension/snapshot.en.md, sites/docs/docs/tutorial/extension/snapshot.zh.md
- 介绍背景
- 三个api如何实现
- 深入探究细节问题
- 总结
=> feat(site): snapshot 实现原理文章

sites/docs/docs/api/detail/index.zh.md, sites/docs/docs/api/index.zh.md
- 完善 getTransform 方法的相关文档
回答 #1729 的时候看文档发现这里写的不是很详细，稍微补充了一下
=> docs: 文档完善

examples/vue3-app/src/utils/math.ts, examples/vue3-app/src/views/PerformanceNode.vue, packages/vue-node-registry/src/model.ts
- 优化获取元素渲染时间方式
- vue-node-registry 中 log 注释掉
=> feat(example&extension): 优化 logicFlow 性能 demo

examples/feature-examples/src/pages/extensions/bpmn/index.less, examples/feature-examples/src/pages/extensions/bpmn/index.tsx, packages/extension/src/bpmn-adapter/index.ts, packages/extension/src/bpmn-elements-adapter/index.ts
- 修复 BpmnAdapter、BPMNAdapter 插件导入含有边的 xml 报错问题 #1823
- 修复 example 中 bpmn demo 用法错误
=> fix(extension): 修复 BpmnAdapter 导入含有边的 xml 报错问题

examples/feature-examples/src/pages/graph/index.tsx
- 修复rect节点中radius属性在properties中使用方式错误
- 新增修改边框颜色button
=> fix(example): 修复rect节点中radius属性在properties中使用方式错误

packages/extension/src/bpmn-elements/presets/Pool/index.ts, sites/docs/docs/tutorial/extension/node-resize.en.md, sites/docs/docs/tutorial/extension/node-resize.zh.md
=> fix(extension/bpmn-elements): 修复bpmn-elements插件中pool节点的node:resize事件取值参数错误的问题

examples/feature-examples/src/pages/graph/index.tsx, packages/extension/src/bpmn-elements/presets/Task/subProcess.ts, packages/vue-node-registry/src/view.ts, sites/docs/docs/api/eventCenter.en.md, sites/docs/docs/api/eventCenter.zh.md
docs: 更新 eventCenter 文档中 node:resize 回调函数参数
fix: 修复 bpmn-elements/Task/subProcess 中 onClick 方法报错的问题 close #1857
fix: 移除 vue-node-registry view 中无用 console，close #1856
=> fix: fix some issues

packages/core/CHANGELOG.md, packages/core/package.json, packages/extension/CHANGELOG.md, packages/extension/package.json, packages/react-node-registry/CHANGELOG.md, packages/react-node-registry/package.json, packages/vue-node-registry/CHANGELOG.md, packages/vue-node-registry/package.json, sites/docs/CHANGELOG.md, sites/docs/package.json
release @logicflow/core@2.0.5
release @logicflow/extension@2.0.9
release @logicflow/react-node-registry@1.0.5
release @logicflow/vue-node-registry@1.0.6
release logicflow-docs@2.0.10
=> feat: update package's version

packages/core/src/event/eventArgs.ts, packages/core/src/model/node/BaseNodeModel.ts
=> fix(core): 类型定义 properties:change 改为 node:properties-change

examples/feature-examples/.umirc.ts, examples/feature-examples/src/pages/background/index.less, examples/feature-examples/src/pages/background/index.tsx, packages/core/src/model/GraphModel.ts, packages/core/src/view/Graph.tsx, packages/core/src/view/overlay/BackgroundOverlay.tsx
1、支持动态修改画布背景配置
2、增加动态修改画布背景配置示例
=> feat: 支持动态修改画布背景配置

examples/feature-examples/src/pages/extensions/node-selection/index.tsx, packages/extension/src/materials/node-selection/index.ts
feat(NodeSelection): 新增 NodeSelection 支持自节点移动或resize时自动更新大小，新增resize NodeSelection 节点时，自
动缩放其关联的子节点
Close #1800
=> feat(NodeSelection): 优化 NodeSelection 功能

packages/core/src/LogicFlow.tsx, packages/core/src/event/eventArgs.ts, packages/core/src/model/GraphModel.ts, packages/extension/src/components/mini-map/index.ts
使用ResizeObserver监听GraphModel中的rootEl大小变化，并新增抛出“graph:resize”事件，MiniMap监听“graph:resize”实现跟随缩放
Closes #1957
=> feat(GraphModel, MiniMap): 新增MiniMap组件跟随的当前容器一起缩放

sites/docs/docs/tutorial/get-started.zh.md
=> docs: 文字缺失

packages/core/src/model/edge/BaseEdgeModel.ts, packages/core/src/view/edge/BaseEdge.tsx, packages/core/src/view/node/BaseNode.tsx, packages/core/src/view/text/BaseText.tsx
=> fix(core): 修复一些issue中提出的问题

examples/feature-examples/src/pages/extensions/menu/index.tsx, packages/extension/src/components/menu/index.ts
#2078 
- 为menu插件中画布菜单选项的回调增加触发画布菜单时鼠标的坐标
- 增加对应的示例
=> feat: menu插件功能完善

examples/feature-examples/src/pages/extensions/dynamic-group/index.tsx, packages/extension/src/components/selection-select/index.ts
在上一个pr https://github.com/didi/LogicFlow/pull/2127 的基础上补充了 独占模式支持单击取消全选 的能力，并修复了测试过程中发现动态分组demo拖拽会报错的问题（上个版本测试的时候改坏了 TvT
=> feat(extension): 独占模式支持单击取消全选

sites/docs/docs/api/detail/index.zh.md
=> docs: fix duplicated title in api docs

examples/feature-examples/src/pages/extensions/proximity-connect/index.tsx, packages/core/src/keyboard/shortcut.ts, packages/core/src/view/node/BaseNode.tsx, packages/extension/src/tools/label/index.ts, packages/extension/src/tools/proximity-connect/index.ts
修复issue反馈的问题 + 内部使用时发现的问题
fix #2210 #2196
=> Bugfix/issues in Aug

packages/core/src/util/resize.ts, packages/core/src/view/Control.tsx
新增节点在选中后按住shift键能够进行等比缩放
效果如下：
=> feat:支持shift节点等比缩放
